
name: Kernel Builder

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        run: pacman -Syu --needed --noconfirm wget make base-devel xmlto llvm lld jdk-openjdk inetutils bc cpio graphviz imagemagick git python3 zip gzip tzdata curl
      - name: Build Kernel
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: |
          export token=${TG_TOKEN}
          export git=${TOKEN}
          export TZ=Asia/Jakarta
          bash build.sh
